---
- name: 'extract zipped backend'
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: 'run node application'
  become: yes
  shell: |
    cd /home/ubuntu
    tar xzvf artifact.tar.gz 

- name: start app
  become: yes
  shell: |
    npm i
    npm run build
    pm2 stop all
    pm2 start npm -- start